image: node:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - your-branch-name
